org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

minecraft_version=26.3
loader_version=0.19.3
loom_version=1.17.20

version=1.8.0
group=dev.mitra

fabric_api_version=0.161.0+26.3
fzzy_config_version=0.7.7+26.3
modmenu_version=21.0.0

releaseDevBuilds=false
