blank_issues_enabled: false
contact_links:
  - name: questions, or something too small for an issue?
    url: https://github.com/Mitra-88/mitras-auto-sprinter/issues/new
    about: not sure if it's a bug open an issue (check existing issues first in case it's already been asked/answered.).
